// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CodeBeautify;
//
//    var welcome4 = Welcome4.FromJson(jsonString);

namespace MyApp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RQuotesModel
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("tags")]
        public string[] Tags { get; set; }

        [JsonProperty("authorSlug")]
        public string AuthorSlug { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("dateAdded")]
        public DateTimeOffset DateAdded { get; set; }

        [JsonProperty("dateModified")]
        public DateTimeOffset DateModified { get; set; }
    }

    public partial class RQuotesModel
    {
        public static RQuotesModel FromJson(string json) => JsonConvert.DeserializeObject<RQuotesModel>(json, MyApp.Models.Converter.Settings);
    }

    public static class Serialize1
    {
        public static string ToJson(this RQuotesModel self) => JsonConvert.SerializeObject(self, MyApp.Models.Converter.Settings);
    }

    internal static class Converter1
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
